apiVersion: v1
kind: Service
metadata:
  name: simple-echo-service-nodeport
spec:
  type: nodePort
  selector:
    app: simple-echo
    customekey: key-value
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6580
      targetPort: 80
      nodePort: 30007
