apiVersion: v1
kind: Service
metadata:
  name: simple-echo-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: simple-echo
    customekey: key-value
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6580
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007